### ISSUE TITLE
Unsubscribe events

### ISSUE THREAD

**Issue by karim-rubix** [adiman9/p5-react-renderer#7]
Hello,

Wonderful job! 
Thought of a small enhancement that might be useful, adding a cleanup to the useP5Event side effect:

`export function useP5Event(event, fn) {`
`  const {subscribe, unsubscribe} = useContext(StateContext);`
`  useEffect(() => {`
`    subscribe(event, fn);`
`    return () => unsubscribe(event, fn);`
`  }, []);`
`}`

to unsubscribe events that won't be used, on subscriber's termination, example unsubscribe method added to state:

`unsubscribe: (event, fn) => {`
`      if (!state.current.subscribers[event]) {`
`        console.error('Attempting to unsubscribe to an unknown event:', event);`
`        return () => {};`
`      }`
`      let index = state.current.subscribers[event].findIndex(s => s === fn);`
`      if (index === -1) {`
`        console.error(`
`          'Attempting to unsubscribe a non existent callback in this event:',`
`          event,`
`        );`
`        return () => {};`
`      }`
`      return state.current.subscribers[event].splice(index, 1);`
`    },`

Thanks in advance :)
Karim

**Comment by adiman9** [comment]
Hey, this is definitely an interesting idea! I will have a look at implementing it when I get some time. 

Thanks for the suggestion!

**Comment by adiman9** [comment]
I have added this feature and pushed the new version to npm.
